- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.2.3
  hooks:
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: check-symlinks
    - id: end-of-file-fixer
    - id: trailing-whitespace

- repo: https://github.com/pre-commit/mirrors-isort
  rev: v4.3.21
  hooks:
    - id: isort  # sort imports

- repo: https://github.com/ambv/black
  rev: 19.3b0
  hooks:
    - id: black  # format Python code

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.2.3
  hooks:
    - id: flake8  # check for style violations
