language: python
python:
  - "3.6"
  - "3.7"
  - "3.8-dev"
  - "nightly"
  - "pypy3"
# command to install dependencies
install: "pip install -e .; pip install pytest"
# command to run tests
script: py.test
